name: MegaPlugin
main: megaplugin.mainClass
version: 1.1c
description: >
            Crafting recipes!
commands:
   storojevayailigonchaya?:
      description: This is a demo command.
      usage: /<command>